---
services:
  db:
    environment:
      MYSQL_DATABASE: db
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: user
    expose:
      - "3307"
    image: "mysql:5.7"
    ports:
      - "3307:3306"
    restart: always
  web:
    build: "."
    depends_on:
      - db
    ports:
      - "5000:5000"
version: "3"
