---
services:
  database:
    env_file:
      - database.env
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - "database-data:/var/lib/postgresql/data/"
  web:
    build: "."
    depends_on:
      - database
    ports:
      - "5000:5000"
version: "3"
volumes:
  database-data: ~
